// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace PCG_Feature5_MLML.Model
{
    public class ModelInput
    {
        [ColumnName("col0"), LoadColumn(0)]
        public string Col0 { get; set; }


        [ColumnName("col1"), LoadColumn(1)]
        public float Col1 { get; set; }


        [ColumnName("col2"), LoadColumn(2)]
        public float Col2 { get; set; }


        [ColumnName("col3"), LoadColumn(3)]
        public float Col3 { get; set; }


        [ColumnName("col4"), LoadColumn(4)]
        public float Col4 { get; set; }


        [ColumnName("col5"), LoadColumn(5)]
        public float Col5 { get; set; }


        [ColumnName("col6"), LoadColumn(6)]
        public float Col6 { get; set; }


        [ColumnName("col7"), LoadColumn(7)]
        public float Col7 { get; set; }


        [ColumnName("col8"), LoadColumn(8)]
        public float Col8 { get; set; }


        [ColumnName("col9"), LoadColumn(9)]
        public float Col9 { get; set; }


        [ColumnName("col10"), LoadColumn(10)]
        public float Col10 { get; set; }


        [ColumnName("col11"), LoadColumn(11)]
        public float Col11 { get; set; }


        [ColumnName("col12"), LoadColumn(12)]
        public float Col12 { get; set; }


        [ColumnName("col13"), LoadColumn(13)]
        public float Col13 { get; set; }


        [ColumnName("col14"), LoadColumn(14)]
        public float Col14 { get; set; }


        [ColumnName("col15"), LoadColumn(15)]
        public float Col15 { get; set; }


        [ColumnName("col16"), LoadColumn(16)]
        public float Col16 { get; set; }


        [ColumnName("col17"), LoadColumn(17)]
        public float Col17 { get; set; }


        [ColumnName("col18"), LoadColumn(18)]
        public float Col18 { get; set; }


        [ColumnName("col19"), LoadColumn(19)]
        public float Col19 { get; set; }


        [ColumnName("col20"), LoadColumn(20)]
        public float Col20 { get; set; }


        [ColumnName("col21"), LoadColumn(21)]
        public float Col21 { get; set; }


        [ColumnName("col22"), LoadColumn(22)]
        public float Col22 { get; set; }


        [ColumnName("col23"), LoadColumn(23)]
        public float Col23 { get; set; }


        [ColumnName("col24"), LoadColumn(24)]
        public float Col24 { get; set; }


        [ColumnName("col25"), LoadColumn(25)]
        public float Col25 { get; set; }


        [ColumnName("col26"), LoadColumn(26)]
        public float Col26 { get; set; }


        [ColumnName("col27"), LoadColumn(27)]
        public float Col27 { get; set; }


        [ColumnName("col28"), LoadColumn(28)]
        public float Col28 { get; set; }


        [ColumnName("col29"), LoadColumn(29)]
        public float Col29 { get; set; }


        [ColumnName("col30"), LoadColumn(30)]
        public float Col30 { get; set; }


        [ColumnName("col31"), LoadColumn(31)]
        public float Col31 { get; set; }


        [ColumnName("col32"), LoadColumn(32)]
        public float Col32 { get; set; }


        [ColumnName("col33"), LoadColumn(33)]
        public float Col33 { get; set; }


        [ColumnName("col34"), LoadColumn(34)]
        public float Col34 { get; set; }


        [ColumnName("col35"), LoadColumn(35)]
        public float Col35 { get; set; }


        [ColumnName("col36"), LoadColumn(36)]
        public float Col36 { get; set; }


        [ColumnName("col37"), LoadColumn(37)]
        public float Col37 { get; set; }


        [ColumnName("col38"), LoadColumn(38)]
        public float Col38 { get; set; }


        [ColumnName("col39"), LoadColumn(39)]
        public float Col39 { get; set; }


        [ColumnName("col40"), LoadColumn(40)]
        public float Col40 { get; set; }


        [ColumnName("col41"), LoadColumn(41)]
        public float Col41 { get; set; }


        [ColumnName("col42"), LoadColumn(42)]
        public float Col42 { get; set; }


        [ColumnName("col43"), LoadColumn(43)]
        public float Col43 { get; set; }


        [ColumnName("col44"), LoadColumn(44)]
        public float Col44 { get; set; }


        [ColumnName("col45"), LoadColumn(45)]
        public float Col45 { get; set; }


        [ColumnName("col46"), LoadColumn(46)]
        public float Col46 { get; set; }


        [ColumnName("col47"), LoadColumn(47)]
        public float Col47 { get; set; }


        [ColumnName("col48"), LoadColumn(48)]
        public float Col48 { get; set; }


        [ColumnName("col49"), LoadColumn(49)]
        public float Col49 { get; set; }


        [ColumnName("col50"), LoadColumn(50)]
        public float Col50 { get; set; }


        [ColumnName("col51"), LoadColumn(51)]
        public float Col51 { get; set; }


        [ColumnName("col52"), LoadColumn(52)]
        public float Col52 { get; set; }


        [ColumnName("col53"), LoadColumn(53)]
        public float Col53 { get; set; }


        [ColumnName("col54"), LoadColumn(54)]
        public float Col54 { get; set; }


        [ColumnName("col55"), LoadColumn(55)]
        public float Col55 { get; set; }


        [ColumnName("col56"), LoadColumn(56)]
        public float Col56 { get; set; }


        [ColumnName("col57"), LoadColumn(57)]
        public float Col57 { get; set; }


        [ColumnName("col58"), LoadColumn(58)]
        public float Col58 { get; set; }


        [ColumnName("col59"), LoadColumn(59)]
        public float Col59 { get; set; }


        [ColumnName("col60"), LoadColumn(60)]
        public float Col60 { get; set; }


        [ColumnName("col61"), LoadColumn(61)]
        public float Col61 { get; set; }


        [ColumnName("col62"), LoadColumn(62)]
        public float Col62 { get; set; }


        [ColumnName("col63"), LoadColumn(63)]
        public float Col63 { get; set; }


        [ColumnName("col64"), LoadColumn(64)]
        public float Col64 { get; set; }


        [ColumnName("col65"), LoadColumn(65)]
        public float Col65 { get; set; }


        [ColumnName("col66"), LoadColumn(66)]
        public float Col66 { get; set; }


        [ColumnName("col67"), LoadColumn(67)]
        public float Col67 { get; set; }


        [ColumnName("col68"), LoadColumn(68)]
        public float Col68 { get; set; }


        [ColumnName("col69"), LoadColumn(69)]
        public float Col69 { get; set; }


        [ColumnName("col70"), LoadColumn(70)]
        public float Col70 { get; set; }


        [ColumnName("col71"), LoadColumn(71)]
        public float Col71 { get; set; }


        [ColumnName("col72"), LoadColumn(72)]
        public float Col72 { get; set; }


        [ColumnName("col73"), LoadColumn(73)]
        public float Col73 { get; set; }


        [ColumnName("col74"), LoadColumn(74)]
        public float Col74 { get; set; }


        [ColumnName("col75"), LoadColumn(75)]
        public float Col75 { get; set; }


        [ColumnName("col76"), LoadColumn(76)]
        public float Col76 { get; set; }


        [ColumnName("col77"), LoadColumn(77)]
        public float Col77 { get; set; }


        [ColumnName("col78"), LoadColumn(78)]
        public float Col78 { get; set; }


        [ColumnName("col79"), LoadColumn(79)]
        public float Col79 { get; set; }


        [ColumnName("col80"), LoadColumn(80)]
        public float Col80 { get; set; }


        [ColumnName("col81"), LoadColumn(81)]
        public float Col81 { get; set; }


        [ColumnName("col82"), LoadColumn(82)]
        public float Col82 { get; set; }


        [ColumnName("col83"), LoadColumn(83)]
        public float Col83 { get; set; }


        [ColumnName("col84"), LoadColumn(84)]
        public float Col84 { get; set; }


        [ColumnName("col85"), LoadColumn(85)]
        public float Col85 { get; set; }


        [ColumnName("col86"), LoadColumn(86)]
        public float Col86 { get; set; }


        [ColumnName("col87"), LoadColumn(87)]
        public float Col87 { get; set; }


        [ColumnName("col88"), LoadColumn(88)]
        public float Col88 { get; set; }


        [ColumnName("col89"), LoadColumn(89)]
        public float Col89 { get; set; }


        [ColumnName("col90"), LoadColumn(90)]
        public float Col90 { get; set; }


        [ColumnName("col91"), LoadColumn(91)]
        public float Col91 { get; set; }


        [ColumnName("col92"), LoadColumn(92)]
        public float Col92 { get; set; }


        [ColumnName("col93"), LoadColumn(93)]
        public float Col93 { get; set; }


        [ColumnName("col94"), LoadColumn(94)]
        public float Col94 { get; set; }


        [ColumnName("col95"), LoadColumn(95)]
        public float Col95 { get; set; }


        [ColumnName("col96"), LoadColumn(96)]
        public float Col96 { get; set; }


        [ColumnName("col97"), LoadColumn(97)]
        public float Col97 { get; set; }


        [ColumnName("col98"), LoadColumn(98)]
        public float Col98 { get; set; }


        [ColumnName("col99"), LoadColumn(99)]
        public float Col99 { get; set; }


        [ColumnName("col100"), LoadColumn(100)]
        public float Col100 { get; set; }


        [ColumnName("col101"), LoadColumn(101)]
        public float Col101 { get; set; }


        [ColumnName("col102"), LoadColumn(102)]
        public float Col102 { get; set; }


        [ColumnName("col103"), LoadColumn(103)]
        public float Col103 { get; set; }


        [ColumnName("col104"), LoadColumn(104)]
        public float Col104 { get; set; }


        [ColumnName("col105"), LoadColumn(105)]
        public float Col105 { get; set; }


        [ColumnName("col106"), LoadColumn(106)]
        public float Col106 { get; set; }


        [ColumnName("col107"), LoadColumn(107)]
        public float Col107 { get; set; }


        [ColumnName("col108"), LoadColumn(108)]
        public float Col108 { get; set; }


        [ColumnName("col109"), LoadColumn(109)]
        public float Col109 { get; set; }


        [ColumnName("col110"), LoadColumn(110)]
        public float Col110 { get; set; }


        [ColumnName("col111"), LoadColumn(111)]
        public float Col111 { get; set; }


        [ColumnName("col112"), LoadColumn(112)]
        public float Col112 { get; set; }


        [ColumnName("col113"), LoadColumn(113)]
        public float Col113 { get; set; }


        [ColumnName("col114"), LoadColumn(114)]
        public float Col114 { get; set; }


        [ColumnName("col115"), LoadColumn(115)]
        public float Col115 { get; set; }


        [ColumnName("col116"), LoadColumn(116)]
        public float Col116 { get; set; }


        [ColumnName("col117"), LoadColumn(117)]
        public float Col117 { get; set; }


        [ColumnName("col118"), LoadColumn(118)]
        public float Col118 { get; set; }


        [ColumnName("col119"), LoadColumn(119)]
        public float Col119 { get; set; }


        [ColumnName("col120"), LoadColumn(120)]
        public float Col120 { get; set; }


        [ColumnName("col121"), LoadColumn(121)]
        public float Col121 { get; set; }


        [ColumnName("col122"), LoadColumn(122)]
        public float Col122 { get; set; }


        [ColumnName("col123"), LoadColumn(123)]
        public float Col123 { get; set; }


        [ColumnName("col124"), LoadColumn(124)]
        public float Col124 { get; set; }


        [ColumnName("col125"), LoadColumn(125)]
        public float Col125 { get; set; }


        [ColumnName("col126"), LoadColumn(126)]
        public float Col126 { get; set; }


        [ColumnName("col127"), LoadColumn(127)]
        public float Col127 { get; set; }


        [ColumnName("col128"), LoadColumn(128)]
        public float Col128 { get; set; }


        [ColumnName("col129"), LoadColumn(129)]
        public float Col129 { get; set; }


        [ColumnName("col130"), LoadColumn(130)]
        public float Col130 { get; set; }


        [ColumnName("col131"), LoadColumn(131)]
        public float Col131 { get; set; }


        [ColumnName("col132"), LoadColumn(132)]
        public float Col132 { get; set; }


        [ColumnName("col133"), LoadColumn(133)]
        public float Col133 { get; set; }


        [ColumnName("col134"), LoadColumn(134)]
        public float Col134 { get; set; }


        [ColumnName("col135"), LoadColumn(135)]
        public float Col135 { get; set; }


        [ColumnName("col136"), LoadColumn(136)]
        public float Col136 { get; set; }


        [ColumnName("col137"), LoadColumn(137)]
        public float Col137 { get; set; }


        [ColumnName("col138"), LoadColumn(138)]
        public float Col138 { get; set; }


        [ColumnName("col139"), LoadColumn(139)]
        public float Col139 { get; set; }


        [ColumnName("col140"), LoadColumn(140)]
        public float Col140 { get; set; }


        [ColumnName("col141"), LoadColumn(141)]
        public float Col141 { get; set; }


        [ColumnName("col142"), LoadColumn(142)]
        public float Col142 { get; set; }


        [ColumnName("col143"), LoadColumn(143)]
        public float Col143 { get; set; }


        [ColumnName("col144"), LoadColumn(144)]
        public float Col144 { get; set; }


        [ColumnName("col145"), LoadColumn(145)]
        public float Col145 { get; set; }


        [ColumnName("col146"), LoadColumn(146)]
        public float Col146 { get; set; }


        [ColumnName("col147"), LoadColumn(147)]
        public float Col147 { get; set; }


        [ColumnName("col148"), LoadColumn(148)]
        public float Col148 { get; set; }


        [ColumnName("col149"), LoadColumn(149)]
        public float Col149 { get; set; }


        [ColumnName("col150"), LoadColumn(150)]
        public float Col150 { get; set; }


        [ColumnName("col151"), LoadColumn(151)]
        public float Col151 { get; set; }


        [ColumnName("col152"), LoadColumn(152)]
        public float Col152 { get; set; }


        [ColumnName("col153"), LoadColumn(153)]
        public float Col153 { get; set; }


        [ColumnName("col154"), LoadColumn(154)]
        public float Col154 { get; set; }


        [ColumnName("col155"), LoadColumn(155)]
        public float Col155 { get; set; }


        [ColumnName("col156"), LoadColumn(156)]
        public float Col156 { get; set; }


        [ColumnName("col157"), LoadColumn(157)]
        public float Col157 { get; set; }


        [ColumnName("col158"), LoadColumn(158)]
        public float Col158 { get; set; }


        [ColumnName("col159"), LoadColumn(159)]
        public float Col159 { get; set; }


        [ColumnName("col160"), LoadColumn(160)]
        public float Col160 { get; set; }


        [ColumnName("col161"), LoadColumn(161)]
        public float Col161 { get; set; }


        [ColumnName("col162"), LoadColumn(162)]
        public float Col162 { get; set; }


        [ColumnName("col163"), LoadColumn(163)]
        public float Col163 { get; set; }


        [ColumnName("col164"), LoadColumn(164)]
        public float Col164 { get; set; }


        [ColumnName("col165"), LoadColumn(165)]
        public float Col165 { get; set; }


        [ColumnName("col166"), LoadColumn(166)]
        public float Col166 { get; set; }


        [ColumnName("col167"), LoadColumn(167)]
        public float Col167 { get; set; }


        [ColumnName("col168"), LoadColumn(168)]
        public float Col168 { get; set; }


        [ColumnName("col169"), LoadColumn(169)]
        public float Col169 { get; set; }


        [ColumnName("col170"), LoadColumn(170)]
        public float Col170 { get; set; }


        [ColumnName("col171"), LoadColumn(171)]
        public float Col171 { get; set; }


        [ColumnName("col172"), LoadColumn(172)]
        public float Col172 { get; set; }


        [ColumnName("col173"), LoadColumn(173)]
        public float Col173 { get; set; }


        [ColumnName("col174"), LoadColumn(174)]
        public float Col174 { get; set; }


        [ColumnName("col175"), LoadColumn(175)]
        public float Col175 { get; set; }


        [ColumnName("col176"), LoadColumn(176)]
        public float Col176 { get; set; }


        [ColumnName("col177"), LoadColumn(177)]
        public float Col177 { get; set; }


        [ColumnName("col178"), LoadColumn(178)]
        public float Col178 { get; set; }


        [ColumnName("col179"), LoadColumn(179)]
        public float Col179 { get; set; }


        [ColumnName("col180"), LoadColumn(180)]
        public float Col180 { get; set; }


        [ColumnName("col181"), LoadColumn(181)]
        public float Col181 { get; set; }


        [ColumnName("col182"), LoadColumn(182)]
        public float Col182 { get; set; }


        [ColumnName("col183"), LoadColumn(183)]
        public float Col183 { get; set; }


        [ColumnName("col184"), LoadColumn(184)]
        public float Col184 { get; set; }


        [ColumnName("col185"), LoadColumn(185)]
        public float Col185 { get; set; }


        [ColumnName("col186"), LoadColumn(186)]
        public float Col186 { get; set; }


        [ColumnName("col187"), LoadColumn(187)]
        public float Col187 { get; set; }


        [ColumnName("col188"), LoadColumn(188)]
        public float Col188 { get; set; }


        [ColumnName("col189"), LoadColumn(189)]
        public float Col189 { get; set; }


        [ColumnName("col190"), LoadColumn(190)]
        public float Col190 { get; set; }


        [ColumnName("col191"), LoadColumn(191)]
        public float Col191 { get; set; }


        [ColumnName("col192"), LoadColumn(192)]
        public float Col192 { get; set; }


        [ColumnName("col193"), LoadColumn(193)]
        public float Col193 { get; set; }


        [ColumnName("col194"), LoadColumn(194)]
        public float Col194 { get; set; }


        [ColumnName("col195"), LoadColumn(195)]
        public float Col195 { get; set; }


        [ColumnName("col196"), LoadColumn(196)]
        public float Col196 { get; set; }


        [ColumnName("col197"), LoadColumn(197)]
        public float Col197 { get; set; }


        [ColumnName("col198"), LoadColumn(198)]
        public float Col198 { get; set; }


        [ColumnName("col199"), LoadColumn(199)]
        public float Col199 { get; set; }


        [ColumnName("col200"), LoadColumn(200)]
        public float Col200 { get; set; }


        [ColumnName("col201"), LoadColumn(201)]
        public float Col201 { get; set; }


        [ColumnName("col202"), LoadColumn(202)]
        public float Col202 { get; set; }


        [ColumnName("col203"), LoadColumn(203)]
        public float Col203 { get; set; }


        [ColumnName("col204"), LoadColumn(204)]
        public float Col204 { get; set; }


        [ColumnName("col205"), LoadColumn(205)]
        public float Col205 { get; set; }


        [ColumnName("col206"), LoadColumn(206)]
        public float Col206 { get; set; }


        [ColumnName("col207"), LoadColumn(207)]
        public float Col207 { get; set; }


        [ColumnName("col208"), LoadColumn(208)]
        public float Col208 { get; set; }


        [ColumnName("col209"), LoadColumn(209)]
        public float Col209 { get; set; }


        [ColumnName("col210"), LoadColumn(210)]
        public float Col210 { get; set; }


        [ColumnName("col211"), LoadColumn(211)]
        public float Col211 { get; set; }


        [ColumnName("col212"), LoadColumn(212)]
        public float Col212 { get; set; }


        [ColumnName("col213"), LoadColumn(213)]
        public float Col213 { get; set; }


        [ColumnName("col214"), LoadColumn(214)]
        public float Col214 { get; set; }


        [ColumnName("col215"), LoadColumn(215)]
        public float Col215 { get; set; }


        [ColumnName("col216"), LoadColumn(216)]
        public float Col216 { get; set; }


        [ColumnName("col217"), LoadColumn(217)]
        public float Col217 { get; set; }


        [ColumnName("col218"), LoadColumn(218)]
        public float Col218 { get; set; }


        [ColumnName("col219"), LoadColumn(219)]
        public float Col219 { get; set; }


        [ColumnName("col220"), LoadColumn(220)]
        public float Col220 { get; set; }


        [ColumnName("col221"), LoadColumn(221)]
        public float Col221 { get; set; }


        [ColumnName("col222"), LoadColumn(222)]
        public float Col222 { get; set; }


        [ColumnName("col223"), LoadColumn(223)]
        public float Col223 { get; set; }


    }
}
